export const namespace = 'ordonnance'

export const dataTypes = {
	INFOS_TEST: 'INFOS_TEST',
	PRESCRIPTIONS: 'PRESCRIPTIONS',
	PRESCRIPTION_CHOISIE: 'PRESCRIPTION_CHOISIE',
	PRESCRIPTION_SAISIE: 'PRESCRIPTION_SAISIE',
	ORDONNANCE_EMISE: 'ORDONNANCE_EMISE'
}